# This is a generated file. Not intended for manual editing.
services:
  expensifier.api:
    build:
      context: "F:\\Development\\Expensifier\\api"
      dockerfile: "Expensifier.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "expensifier.api:dev"
    ports:
    - "127.0.0.1:57007:57100"
    - "127.0.0.1:57207:57300"
    volumes:
    - "C:\\Users\\micha\\.nuget\\packages:/home/app/.nuget/packages"
    - "F:\\Development\\Expensifier\\api\\Expensifier.API:/app:rw"
    - "F:\\Development\\Expensifier\\api:/src:rw"
    - "C:\\Users\\micha\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1EAP9D\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\micha\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\micha\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_5_08_21_33_24:/var/opt/rider-debugger:rw"
    working_dir: "/app"
