services:
  expensifier.api:
    image: expensifier.api
    build:
      context: .
      dockerfile: Expensifier.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      expensifier.database:
        condition: service_healthy
  
  expensifier.database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: Expensifier
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./.containers/expensifier-database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: