name: .NET

on:
  push:
    branches: [ "main" ]
    paths: [ "api/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "api/**" ]
  workflow_dispatch:
    

jobs:
  build:
    defaults:
      run:
        working-directory: ./api
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      - name: Echo version
        run: |
          echo Pushing mrnustik/expensifier-api:${{ vars.VERSION }}.${{ github.run_number }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Expensifier.API/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mrnustik/expensifier-api:v${{ vars.VERSION }}.${{ github.run_number }}
          provenance: true
          sbom: true
      - name: Create git tag
        run: |
          git tag api-v${{ vars.VERSION }}.${{ github.run_number }}
      - name: Push git tag
        run: git push origin api-v${{ vars.VERSION }}.${{ github.run_number }}
      - name: Update api version
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'deployment/expensifier/values.yaml'
          propertyPath: 'backend.version'
          value: v${{ vars.VERSION }}.${{ github.run_number }}
          commitChange: true
          branch: 'main'
          message: "Release api v${{ vars.VERSION }}.${{ github.run_number }}"
